---
version: 2
mergeable:
  - when: pull_request.*, pull_request_review.*
    validate:
      - do: title
        must_exclude:
          regex: ^\[WIP\]
      - do: description
        must_exclude:
          regex: \[ \]
          message: There are incomplete TODO task(s) unchecked.
  - when: pull_request.*, pull_request_review.*
    validate:
      - do: headRef
        must_include:
          regex: '.+'
          message: 'Your branch name can contain anything'