---
version: 2
mergeable:
  - when: pull_request.*, pull_request_review.*
    name: 'checkfirst'
    validate:
      - do: title
        jira:
          enabled: true
        must_exclude:
          regex: ^\[WIP\]