version: 2
whitelist:
  - hellofresh/mergeable-automation
mergeable:
  - when: pull_request.*, pull_request_review.*
    validate:
      - do: title
        # Enforce semantic release convention.
        must_include:
          regex: muho
          message: Semantic release conventions must be followed.
        # All todo check boxes must be checked.