---
version: 2
mergeable:
  - when: pull_request.*, pull_request_review.*
    name: 'Organization'
    validate:
      - do: title
        must_exclude:
          regex: ^\[WIP\]
      - do: description
        must_exclude:
          regex: \[ \]
          message: There are incomplete TODO task(s) unchecked.